<style type="text/css">
	.content {
		padding-bottom:20px;
	}
</style>
<div>
<?php printf(__('Have you enabled Goal for your MailChimp account?  <a href="%s">Log in</a> to your MailChimp account and check your "Integrations" page to make sure.', 'goalWP'), 'http://login.mailchimp.com');?>
</div>
<div class="content">
	<h3><?php echo __('What is Goal?', 'goalWP');?></h3><?php printf(__('Goal is an optional campaign tracking feature available for paid MailChimp accounts that lets you trigger <a href="%s">autoresponders</a> based on subscriber activity from your email campaigns to your website. The Goal integration can also be used to create segments of subscribers allowing you to send targeted campaigns to your subscribers based on their Goal activity.', 'goalWP'), 'http://kb.mailchimp.com/article/how-do-i-create-an-autoresponder/');?>
</div>
<div class="content">
	<a href="http://kb.mailchimp.com/article/how-do-i-use-goals-tracking/#how"><?php _e('Read more about Goal.', 'goalWP');?></a>
</div>
<div class="content">
	<h3><?php echo __('How do I connect my MailChimp account?', 'goalWP');?></h3><?php printf(__('To connect to MailChimp, you\'ll need to grab an <a href="%s">API Key</a> from your account.  Only API Keys generated by <strong>Owner</strong> or <strong>Admin</strong> level users will be able to connect to get the necessary data.', 'goalWP'), 'http://kb.mailchimp.com/article/where-can-i-find-my-api-key');?>
</div>
<div class="content">
	<form method="post" action="<?php echo str_replace( '%7E', '~', $_SERVER['REQUEST_URI']); ?>">
		<input type="text" name="mcapi" placeholder="MailChimp API Key" required>
		<input type="submit" class="">
	</form>
</div>